# Generated by Django 4.0.4 on 2022-11-18 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('document_type', models.CharField(choices=[('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Tarjeta de extranjería', 'Tarjeta de extranjería'), ('Cédula de extranjería', 'Cédula de extranjería'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], max_length=40, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
            ],
        ),
    ]
