# Generated by Django 4.0.4 on 2022-11-18 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Sesión', 'Sesión'), ('Semana', 'Semana'), ('Quincena', 'Quincena'), ('Mes', 'Mes')], max_length=40, verbose_name='Tipo de pago')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('Pendiente', 'Pendiente')], max_length=40, verbose_name='Estado')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('date_joined', models.DateField(verbose_name='Fecha')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
    ]
